cloud:
    aws:
        region:
            static: ap-south-1
            auto: false
        credentials:
            access-key: AKIARBKK4UBPDQYL5APL
            secret-key: 8pSz1YJP3bbLjNZgRkKDgwu+SHtjAIVHPQk/egIU
        end-point:
            uri: https://sqs.ap-south-1.amazonaws.com/071560896606/springboot-sqs-example